# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mattgreen
email: mjgreen145@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm a developer currently working at Net-A-Porter.
  I have a keen interest in all things Web, with a particular focus on web performance.
  Blog posts will be a collection of my findings/musings on this subject. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattgreen.io" # the base hostname & protocol for your site
twitter_username: mjgreen145
github_username:  mjgreen145

# Build settings
markdown: kramdown
